openapi: 3.0.3
info:
  title: Transevilz API
  description: Dokumentasi untuk menggunakan API aplikasi Transevilz
  version: 1.0.11
servers:
- url: https://red-gifted-squid.cyclic.app
tags:
- name: Mobile API
  description: List of endpoint that use to hit mobile api
- name: Backoffice API
  description: Access to Petstore orders
paths:
  /api/v1/otp_verification:
    post:
      tags:
      - Mobile API
      summary: OTP
      description: gunakan untuk melakukan verifikasi dengan OTP
      operationId: apiV1Otp_verificationPOST
      requestBody:
        description: Semantara belum ada proses verifikasi nyata. masih menggunakan
          harcoded **Code**. gunakan `otp_code:`**102030**
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Otp'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-swagger-router-controller: MobileAPI
  /api/v1/register:
    post:
      tags:
      - Mobile API
      summary: Register user
      description: register user.
      operationId: apiV1RegisterPOST
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400_1'
      x-swagger-router-controller: MobileAPI
  /api/v1/login:
    post:
      tags:
      - Mobile API
      summary: Login user
      description: login user.
      operationId: apiV1LoginPOST
      requestBody:
        description: login object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_login_body'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400_2'
      x-swagger-router-controller: MobileAPI
  /api/v1/pin:
    post:
      tags:
      - Mobile API
      summary: Create user pin
      description: Need `bearer authorization` as header
      operationId: apiV1PinPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_pin_body'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_2'
        "400":
          description: failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400_3'
      x-swagger-router-controller: MobileAPI
  /api/v1/new_password:
    put:
      tags:
      - Mobile API
      summary: Create new password
      description: "tidak pake header, cukup email valid"
      operationId: apiV1New_passwordPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_new_password_body'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_3'
      x-swagger-router-controller: MobileAPI
  /api/v1/new_pin:
    put:
      tags:
      - Mobile API
      summary: Create new Pin
      description: butuh header authorization
      operationId: apiV1New_pinPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_new_pin_body'
      responses:
        "201":
          description: successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_4'
      x-swagger-router-controller: MobileAPI
  /api/v1/receipent:
    get:
      tags:
      - Mobile API
      summary: GET receipent
      description: butuh token
      operationId: apiV1ReceipentGET
      parameters:
      - name: bank_code
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: no_rekening
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-swagger-router-controller: MobileAPI
  /api/v1/transactions:
    post:
      tags:
      - Mobile API
      summary: Create transaction
      description: Need `bearer authorization` as header
      operationId: apiV1TransactionsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_transactions_body'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_5'
      x-swagger-router-controller: MobileAPI
  /api/v1/transactions/{transaction_id}:
    get:
      tags:
      - Mobile API
      summary: Create transaction
      description: Need `bearer authorization` as header
      operationId: apiV1TransactionsTransaction_idGET
      parameters:
      - name: transaction_id
        in: path
        description: ID of pet to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
      x-swagger-router-controller: MobileAPI
  /api/v1/myTransaction:
    get:
      tags:
      - Mobile API
      summary: Create transaction
      description: Need `bearer authorization` as header
      operationId: apiV1MyTransactionGET
      responses:
        "200":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_2'
                x-content-type: application/json
      x-swagger-router-controller: MobileAPI
  /api/backoffice/users:
    get:
      tags:
      - Backoffice API
      operationId: apiBackofficeUsersGET
      responses:
        "200":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
      x-swagger-router-controller: BackofficeAPI
    post:
      tags:
      - Backoffice API
      operationId: apiBackofficeUsersPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400_1'
      x-swagger-router-controller: BackofficeAPI
  /api/backoffice/users/{user_id}:
    put:
      tags:
      - Backoffice API
      operationId: apiBackofficeUsersUser_idPUT
      parameters:
      - name: user_id
        in: path
        description: ID of pet to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: successful operation. di response juga nanti ada `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_6'
        "400":
          description: failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400_1'
      x-swagger-router-controller: BackofficeAPI
    delete:
      tags:
      - Backoffice API
      operationId: apiBackofficeUsersUser_idDELETE
      parameters:
      - name: user_id
        in: path
        description: ID of pet to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: if deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
      x-swagger-router-controller: BackofficeAPI
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: andika@mail.com
        doc_type:
          type: string
          description: only `ktp` or `sim` or `passport`
          example: ktp
        doc_number:
          type: integer
          example: 123456781727364750
        firstname:
          type: string
          example: andi
        lastname:
          type: string
          example: ka
        birth_place:
          type: string
          example: surakarta
        birth_date:
          type: string
          description: format dd/mm/yyyy
          example: 10/02/2022
        address:
          type: string
          example: jln. magelang no.5
        phone_number:
          type: string
          example: "343434343434"
        password:
          type: string
          example: myPassWD
        sex:
          type: string
          description: only `male` or `female`
          example: male
      example:
        firstname: andi
        password: myPassWD
        address: jln. magelang no.5
        birth_date: 10/02/2022
        sex: male
        doc_number: 123456781727364750
        birth_place: surakarta
        phone_number: "343434343434"
        doc_type: ktp
        email: andika@mail.com
        lastname: ka
    Otp:
      required:
      - otp_code
      type: object
      properties:
        otp_code:
          type: string
          example: "102030"
    inline_response_200:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          example: otp verification success!
      example:
        message: otp verification success!
        status: success
    inline_response_400:
      type: object
      properties:
        status:
          type: string
          example: failed
        message:
          example: otp verification error!
    inline_response_201:
      type: object
      properties:
        message:
          type: string
          example: user created
      example:
        message: user created
    inline_response_400_1:
      type: object
      properties:
        message:
          type: string
          example: email already registered
    v1_login_body:
      type: object
      properties:
        email:
          type: string
          example: ahmad@gmail.com
        password:
          type: string
          example: niza5r
    inline_response_201_1:
      type: object
      properties:
        accessToken:
          type: string
          example: kkjasdkhdhasldoicawoeiji2j3oijlkas
        expiresIn:
          type: integer
          description: token expired pada
          example: 2934234
        user:
          $ref: '#/components/schemas/inline_response_201_1_user'
      example:
        expiresIn: 2934234
        accessToken: kkjasdkhdhasldoicawoeiji2j3oijlkas
        user:
          userPin: false
          id: kajsdf-asdf-asdf23-asd-aasd
          fullname: ahmad nizar
          email: ahmad@gmail.com
    inline_response_400_2:
      type: object
      properties:
        status:
          type: string
          example: failed to login
        message:
          type: string
          example: email or password invalid
    v1_pin_body:
      type: object
      properties:
        pin:
          type: integer
          example: 102030
    inline_response_201_2:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: pin created
      example:
        message: pin created
        status: success
    inline_response_400_3:
      type: object
      properties:
        status:
          type: string
          example: failed
        message:
          type: string
          example: user already have pin
    v1_new_password_body:
      type: object
      properties:
        password:
          type: string
          example: newPass_word
        email:
          type: string
          example: email@mail.com
    inline_response_201_3:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: password updated
      example:
        message: password updated
        status: success
    v1_new_pin_body:
      type: object
      properties:
        pin:
          type: string
          example: "909090"
    inline_response_201_4:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: pin updated
      example:
        message: pin updated
        status: success
    inline_response_200_1:
      type: object
      properties:
        name:
          type: string
          example: ANdika
      example:
        name: ANdika
    v1_transactions_body:
      type: object
      properties:
        pin:
          type: integer
          example: 102030
        bank_code:
          type: string
          example: "111"
        no_rekening:
          type: string
          example: "720200009304145"
        nominal:
          type: string
          example: "90000000"
    inline_response_201_5:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: transaction created
        data:
          $ref: '#/components/schemas/inline_response_201_5_data'
      example:
        data:
          transaction_id: 1c38b63e-c2a4-4490-acc1-322796a6b284
        message: transaction created
        status: success
    inline_response_200_2:
      type: object
      properties:
        id:
          type: string
          example: asdfasdf
        receipent_name:
          type: string
          example: adi
        bank:
          type: string
          example: CIMB Niaga
        type_currency:
          type: string
          example: IDR to IDR
        type_transaction:
          type: string
          example: Lokal
        receipent_norek:
          type: string
          example: "720200009304145"
        virtual_account:
          type: string
          example: 4806-4156-3950-6506-792
        total:
          type: string
          example: "9005000"
        nominal:
          type: string
          example: "9000000"
        status:
          type: string
          example: In Progress
        admin_fee:
          type: string
          example: "5000"
        transaction_date:
          type: string
          example: 2023-01-16T07:46:59.092Z
        expired_at:
          type: string
          example: 2023-01-17T07:46:59.093Z
        isExpired:
          type: string
          example: "false"
      example:
        transaction_date: 2023-01-16T07:46:59.092Z
        admin_fee: "5000"
        expired_at: 2023-01-17T07:46:59.093Z
        receipent_name: adi
        type_transaction: Lokal
        bank: CIMB Niaga
        total: "9005000"
        nominal: "9000000"
        virtual_account: 4806-4156-3950-6506-792
        type_currency: IDR to IDR
        id: asdfasdf
        isExpired: "false"
        receipent_norek: "720200009304145"
        status: In Progress
    inline_response_201_6:
      type: object
      properties:
        message:
          type: string
          example: user updated
      example:
        message: user updated
    inline_response_200_3:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: user deleted
      example:
        message: user deleted
        status: success
    inline_response_201_1_user:
      type: object
      properties:
        id:
          type: string
          example: kajsdf-asdf-asdf23-asd-aasd
        email:
          type: string
          example: ahmad@gmail.com
        fullname:
          type: string
          example: ahmad nizar
        userPin:
          type: boolean
          example: false
      example:
        userPin: false
        id: kajsdf-asdf-asdf23-asd-aasd
        fullname: ahmad nizar
        email: ahmad@gmail.com
    inline_response_201_5_data:
      type: object
      properties:
        transaction_id:
          type: string
          example: 1c38b63e-c2a4-4490-acc1-322796a6b284
      example:
        transaction_id: 1c38b63e-c2a4-4490-acc1-322796a6b284
